### ISSUE TITLE
Implement performance automation scripts

### ISSUE THREAD

**Issue by tjcw** [ykt-networking/ebpf-performance#1]

**Comment by huang195** [comment]
1. Evaluate different CNIs
- kind-cni (default)
- bash-cni (ours - use noxdp)
- flannel
- cilium
- calico

2. Automate
- Setting up kind clusters
- Install CNI
- Run iperf3 workload
- Collect CPU/memory data
- Collect perf data for flamegraph
- Generate the data graph
- git commit data into a repo
